"use client";

import { motion } from "framer-motion";
import MacbookMockup from "./MacbookMockup";

const fadeUp = { initial: { opacity: 0, y: 24 }, animate: { opacity: 1, y: 0 } };

/* Dashboard content shown inside the MacBook screen */
function DashboardScreen() {
  return (
    <div className="w-full bg-white" style={{ minHeight: 340 }}>
      {/* App sidebar + main */}
      <div className="flex h-full" style={{ minHeight: 340 }}>
        {/* Sidebar */}
        <div className="w-40 flex-shrink-0 bg-[#FAFAF8] border-r border-[#F0EBE1] p-4 flex flex-col gap-1 pt-8">
          {["Dashboard", "Automations", "Contacts", "Broadcasts", "Analytics", "Settings"].map((item, i) => (
            <div
              key={item}
              className={`px-3 py-2 rounded-lg text-[10px] font-medium ${
                i === 0 ? "bg-[#1A1411] text-white" : "text-[#9C8F83]"
              }`}
            >
              {item}
            </div>
          ))}
        </div>

        {/* Main content */}
        <div className="flex-1 p-5 flex flex-col gap-4">
          {/* Header */}
          <div className="flex items-center justify-between">
            <div>
              <p className="text-[9px] text-[#9C8F83] uppercase tracking-wider mb-0.5">
                May 2026 · Revenue generated by Tellero
              </p>
              <p
                className="font-bold text-[#25D366]"
                style={{ fontSize: 26 }}
              >
                ₹84,000
              </p>
            </div>
            <div className="px-3 py-1.5 bg-[#F4FEF8] border border-[#25D366]/25 rounded-lg">
              <p className="text-[9px] text-[#25D366] font-bold">ROI: 10,513%</p>
            </div>
          </div>

          {/* Revenue cards */}
          <div className="grid grid-cols-2 gap-2">
            {[
              { label: "Recovered carts", value: "₹34,200", count: "43 orders", color: "#F4FEF8" },
              { label: "Prevented COD loss", value: "₹12,600", count: "67 orders", color: "#FEF9F0" },
              { label: "Reorder revenue", value: "₹28,800", count: "38 orders", color: "#F8F4FE" },
              { label: "Win-back campaigns", value: "₹8,400", count: "12 customers", color: "#F4F8FE" },
            ].map((card) => (
              <div
                key={card.label}
                className="p-3 rounded-xl border border-[#1A1411]/06"
                style={{ background: card.color }}
              >
                <p className="text-[9px] text-[#9C8F83] mb-0.5">{card.label}</p>
                <p className="text-[11px] font-bold text-[#1A1411]">{card.value}</p>
                <p className="text-[9px] text-[#C5B9AD]">{card.count}</p>
              </div>
            ))}
          </div>

          {/* Bottom total */}
          <div className="flex items-center justify-between pt-3 border-t border-[#F0EBE1]">
            <p className="text-[9px] text-[#9C8F83]">Subscription: ₹799/month</p>
            <p className="text-[11px] font-bold text-[#25D366]">Total: ₹84,000</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function Hero() {
  return (
    <section className="section-cream relative min-h-screen flex flex-col items-center justify-center pt-24 pb-0 px-6 overflow-hidden">
      <div className="relative z-10 max-w-4xl mx-auto text-center">
        {/* Badge */}
        <motion.div
          {...fadeUp}
          transition={{ duration: 0.5 }}
          className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-[rgba(26,20,17,0.14)] bg-white/70 mb-8"
        >
          <span className="w-1.5 h-1.5 rounded-full bg-[#25D366] animate-pulse" />
          <span className="label" style={{ color: "var(--text-dark)" }}>
            AI-native · Built for Indian D2C brands
          </span>
        </motion.div>

        {/* Headline */}
        <motion.h1
          {...fadeUp}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="heading-hero text-[var(--text-dark)] mb-6"
        >
          Revenue&apos;s secret{" "}
          <span className="text-[#25D366]">ingredient.</span>
        </motion.h1>

        {/* Sub-headline */}
        <motion.p
          {...fadeUp}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="body-lg max-w-[540px] mx-auto mb-10"
        >
          Meet the WhatsApp revenue engine built for Indian D2C brands. AI that
          cuts COD returns by 40%, recovers abandoned carts automatically, and
          reminds your customers to reorder — before they forget you.
        </motion.p>

        {/* CTAs */}
        <motion.div
          {...fadeUp}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="flex flex-col sm:flex-row items-center justify-center gap-3 mb-5"
        >
          <a href="#" className="btn btn-dark w-full sm:w-auto">
            Start for free — no credit card
          </a>
          <a href="#features" className="btn btn-outline w-full sm:w-auto">
            See how it works →
          </a>
        </motion.div>

        {/* Micro proof */}
        <motion.p
          {...fadeUp}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="body-sm"
          style={{ color: "var(--text-muted)" }}
        >
          Free forever plan · Setup in 10 minutes · No credit card required
        </motion.p>
      </div>

      {/* MacBook mockup */}
      <motion.div
        initial={{ opacity: 0, y: 56 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.9, delay: 0.55 }}
        className="relative z-10 mt-16 w-full max-w-4xl mx-auto"
      >
        <MacbookMockup>
          <DashboardScreen />
        </MacbookMockup>
      </motion.div>
    </section>
  );
}
