-- ============================================================
-- Migration 13 — Feature 6: COD Confirmation Automation
-- Adds cod_settings to profiles, creates cod_confirmations,
-- and extends automation_queue to support cod_timeout events.
-- Requires: migration 10 (shopify / automation_queue).
-- ============================================================

-- ── 1. Add cod_settings JSONB to profiles ───────────────────
-- Shape: { enabled, confirmation_window_hours, on_no_reply, on_no, template_name }
alter table public.profiles
  add column if not exists cod_settings jsonb;

comment on column public.profiles.cod_settings is
  'COD confirmation automation settings. Shape: { enabled: boolean, confirmation_window_hours: number, on_no_reply: "cancel"|"flag", on_no: "cancel"|"flag", template_name: string }';


-- ── 2. cod_confirmations ─────────────────────────────────────
-- Tracks every COD confirmation message sent to a customer.
-- Inserted by the cron processor when a cod_confirmation queue item fires.
-- Updated by the Meta webhook when the customer replies YES/NO.
create table if not exists public.cod_confirmations (
  id                     uuid        primary key default gen_random_uuid(),
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  user_id                uuid        not null references public.profiles (id) on delete cascade,
  order_id               uuid        references public.orders (id) on delete cascade,
  automation_queue_id    uuid        references public.automation_queue (id) on delete set null,

  -- Phone stored without + prefix (same format as automation_queue.recipient_phone)
  customer_phone         text        not null,

  -- Lifecycle status
  status                 text        not null default 'pending'
    check (status in ('pending', 'confirmed', 'cancelled', 'no_reply', 'failed')),

  customer_reply         text,                  -- actual reply text sent by customer
  shopify_order_cancelled boolean    not null default false,

  sent_at                timestamptz not null default now(),
  replied_at             timestamptz,
  resolved_at            timestamptz
);

comment on table public.cod_confirmations is
  'One row per COD confirmation message sent. Updated when customer replies or timeout fires.';

-- Updated-at trigger (reuses the set_updated_at function from migration 01)
drop trigger if exists cod_confirmations_updated_at on public.cod_confirmations;
create trigger cod_confirmations_updated_at
  before update on public.cod_confirmations
  for each row execute procedure public.set_updated_at();

-- Indexes
create index if not exists cod_confirmations_user_id_idx
  on public.cod_confirmations (user_id);

-- Composite index for the Meta webhook lookup (phone + status)
create index if not exists cod_confirmations_phone_status_idx
  on public.cod_confirmations (customer_phone, status)
  where status = 'pending';

create index if not exists cod_confirmations_order_id_idx
  on public.cod_confirmations (order_id);

-- RLS
alter table public.cod_confirmations enable row level security;

create policy "cod_confirmations: owner select"
  on public.cod_confirmations for select
  using (auth.uid() = user_id);

-- Inserts and updates come from the cron and Meta webhook (service role → bypasses RLS)


-- ── 3. Extend automation_queue event_type to include cod_timeout ─
-- Drop the existing inline CHECK constraint and re-add with the new value.
-- The constraint name is auto-generated by Postgres as {table}_{col}_check.
alter table public.automation_queue
  drop constraint if exists automation_queue_event_type_check;

alter table public.automation_queue
  add constraint automation_queue_event_type_check
  check (event_type in (
    'cod_confirmation',
    'cod_timeout',
    'abandoned_cart',
    'order_confirmed',
    'order_shipped',
    'order_cancelled',
    'reorder_reminder',
    'win_back'
  ));
